# Use official .NET 8 SDK image to build the app
FROM mcr.microsoft.comdotnetsdk8.0 AS build

WORKDIR app

# Copy everything into the container
COPY . .

# Publish the application to out folder
RUN dotnet publish -c Release -o out

# Use the ASP.NET runtime image for running the app
FROM mcr.microsoft.comdotnetaspnet8.0 AS runtime

WORKDIR app

# Copy published app from build stage
COPY --from=build appout .

# Expose port 80 (default HTTP port)
EXPOSE 80

# Start the application
ENTRYPOINT [dotnet, FlourMillApi.dll]
